local to_dump = {{name="bit", table=bit}, {name="client", table=client}, {name="database", table=database}, {name="entity", table=entity}, {name="globals", table=globals}, {name="materialsystem", table=materialsystem},{name="renderer", table=renderer}, {name="ui", table=ui}, {name="math", table=math}, {name="table", table=table}, {name="string", table=string}}
local table_insert = table.insert
local table_remove = table.remove
local table_concat = table.concat
local string_len = string.len
local math_ceil = math.ceil

local function log_raw(message)
	client.exec("echo \"", message, "\"")
end

local function dump_api()
	client.log("Copy and paste this into your script:")
	log_raw("--local variables for API. Automatically generated byhttps://github.com/Velortex/gamesenseLUA/blob/main/generate_api.lua")
	log_raw("local api = {");
	for i=1, #to_dump do
		local global = to_dump[i]["table"]
		local name = to_dump[i]["name"]
		log_raw("  " .. name .. "= {");
		for i,v in pairs(global) do
			log_raw("    " .. i .. " = "..name.. "." .. i ..",");
		end
		log_raw("  },");
	end
	log_raw("}");
	log_raw("--end of local variables")
end

ui.new_button("CONFIG", "Lua", "Generate API local variables", dump_api)
